wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.9
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1751338061
    t:
      1:
      - 55
      3:
      - 23
      4: 3.11.9
      5: 0.17.9
      8:
      - 5
      13: linux-x86_64
